# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('coordinates', models.CharField(blank=True, help_text='lat,lon', max_length=64)),
                ('summary', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('Startup', 'Startup'), ('Digital agency', 'Digital agency'), ('Small bussiness', 'Small business'), ('Medium bussiness', 'Medium business'), ('Big bussiness', 'Big business'), ('Non-profit', 'Non-profit')], max_length=64, verbose_name='Company size')),
                ('employees', models.CharField(choices=[('1 - 5', '1 - 5'), ('5 - 10', '5 - 10'), ('10 - 100', '10 - 100'), ('100+', '100+')], max_length=64, verbose_name='Quantity of employees')),
                ('contact_name', models.CharField(max_length=128, verbose_name='Contact name')),
                ('contact_email', models.CharField(max_length=128, verbose_name='Contact email')),
                ('contact_phone', models.CharField(max_length=128, verbose_name='Contact phone')),
                ('contact_position', models.CharField(max_length=128, verbose_name='Contact position')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
