# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_organization'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Certification')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('in_progress', models.BooleanField(default=False)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Certification')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Degree')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('in_progress', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Institution')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('in_progress', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Organization')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('coordinates', models.CharField(blank=True, help_text='lat,lon', max_length=64)),
                ('salary_min', models.IntegerField(blank=True, help_text='S/', null=True, verbose_name='Minimum Salary')),
                ('job_type', models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Onsite or Remote', 'Onsite or Remote')], max_length=32, verbose_name='Preference of type of employment')),
                ('type_of_contract', models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Contract or Permanent', 'Contract or Permanent')], max_length=32, verbose_name='Preference of type of contract')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title or resume')),
                ('url', models.CharField(blank=True, max_length=256, verbose_name='Online URL, app store link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('description', models.TextField(help_text='Describe the software or feature and what your contribution was.')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'User Project',
                'verbose_name_plural': 'User Projects',
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='UserURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('Web', 'Web'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Gitlab', 'Gitlab'), ('Twitter', 'Twitter'), ('StackOverflow', 'StackOverflow'), ('Linkedin', 'Linkedin'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=32)),
                ('url', models.CharField(max_length=64, verbose_name='Profile url or Username')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'User Url',
                'verbose_name_plural': 'User Urls',
            },
        ),
        migrations.AddField(
            model_name='userjob',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
