# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjob',
            options={'ordering': ('-start_date', '-end_date'), 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
